# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HPWVistorRemoteTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # pod 'HPWVistor', '~> 2.6.12’
  # Pods for HPWVistorRemoteTest

end
